version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: etl_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  etl:
    build: .
    container_name: etl_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: etl_user
      DB_PASSWORD: etl_password
      DB_NAME: etl
      DB_PORT: 3306
    command: ["python", "scripts/load.py"]

volumes:
  mysql_data:
